FROM nginx:1.10.3-alpine@sha256:4aacdcf186934dcb02f642579314075910f1855590fd3039d8fa4c9f96e48315

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

COPY ./conf/nginx-site.conf /etc/nginx/conf.d/default.conf
