FROM nginx:1.12.2-alpine@sha256:812dd32216edcfd41decaacc8fe7cae80b39e5a87b0b8923bc15c4db94cf5bdb

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

COPY ./conf/nginx-site.conf /etc/nginx/conf.d/default.conf
