FROM nginx:1.11.9-alpine@sha256:d34e2176dab830485b0cb79340e1d5ebf7d530b34ad7bfe05d269ffed20a88f4

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

COPY ./conf/nginx-site.conf /etc/nginx/conf.d/default.conf
